package org.adaway.model.root

import java.security.MessageDigest

/**
 * The fingerprint of everything that determines the content of the generated hosts file.
 *
 * The generated file embeds its own fingerprint as a header line. Regenerating it is only skipped
 * when the fingerprint read back from the file equals the one computed from the current inputs,
 * so the cached file is reused only on positive proof that it is still correct. Any doubt, such as
 * a missing file, an unreadable header or an unrecognised format, yields no fingerprint and
 * therefore a regeneration.
 */
object HostsFingerprint {
    /**
     * The header line carrying the fingerprint.
     */
    private const val HEADER_PREFIX = "# AdAway fingerprint: "

    /**
     * The version of the generated file layout.
     * Bump it whenever the way the hosts file is written changes, so files generated by a previous
     * version are never reused.
     */
    private const val FORMAT_VERSION = "1"

    /**
     * Compute the fingerprint of the hosts file content.
     *
     * Every value that the generator reads must be an input here. The revision changes whenever the
     * host entries are rebuilt, and the entry count is included as an independent cross check: a
     * write path that ever forgets to update the revision still changes the number of entries in
     * all but the most contrived cases.
     *
     * @param entriesRevision The revision of the host entries, as recorded by the last rebuild.
     * @param entryCount The number of host entries.
     * @param redirectionIpv4 The IPv4 address blocked hosts are redirected to.
     * @param redirectionIpv6 The IPv6 address blocked hosts are redirected to.
     * @param ipv6Enabled Whether an IPv6 line is written for each blocked host.
     * @param enabledSources The identity of each enabled source, as written in the file header.
     * @return The fingerprint, as a hexadecimal string.
     */
    @JvmStatic
    fun compute(
        entriesRevision: String,
        entryCount: Int,
        redirectionIpv4: String,
        redirectionIpv6: String,
        ipv6Enabled: Boolean,
        enabledSources: List<String>
    ): String {
        val digest = MessageDigest.getInstance("SHA-256")
        // Each input is length prefixed so that no two different input sets can produce the same
        // byte stream by shifting content across boundaries.
        for (part in listOf(
            FORMAT_VERSION,
            entriesRevision,
            entryCount.toString(),
            redirectionIpv4,
            redirectionIpv6,
            ipv6Enabled.toString(),
            enabledSources.size.toString()
        ) + enabledSources) {
            val bytes = part.toByteArray(Charsets.UTF_8)
            digest.update(bytes.size.toString().toByteArray(Charsets.UTF_8))
            digest.update(0)
            digest.update(bytes)
            digest.update(0)
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }

    /**
     * Build the header line embedding a fingerprint.
     *
     * @param fingerprint The fingerprint to embed.
     * @return The header line, without its line separator.
     */
    @JvmStatic
    fun toHeaderLine(fingerprint: String): String = HEADER_PREFIX + fingerprint

    /**
     * Extract the fingerprint from the header of a generated hosts file.
     *
     * @param lines The first lines of the file.
     * @return The fingerprint, or {@code null} if the header does not carry a readable one.
     */
    @JvmStatic
    fun fromHeaderLines(lines: Iterable<String>): String? {
        for (line in lines) {
            if (!line.startsWith(HEADER_PREFIX)) {
                continue
            }
            val value = line.substring(HEADER_PREFIX.length).trim()
            return value.takeIf { it.isNotEmpty() && it.all(::isHexDigit) }
        }
        return null
    }

    private fun isHexDigit(character: Char): Boolean {
        return character in '0'..'9' || character in 'a'..'f' || character in 'A'..'F'
    }
}
